"""
Canonical QA schema — the normalized representation every source maps into.

All data sources (Stack Exchange, SQuAD, NQ, etc.) produce CanonicalQA records.
This is the source-of-truth model for downstream chunking, embedding, and graph extraction.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from .provenance import License, SourceName


class EntityMention(BaseModel):
    """A named entity found in a question or answer body."""
    surface_form: str
    entity_type: str                    # PERSON, ORG, LOC, MISC, etc. (spaCy labels)
    start_char: int
    end_char: int
    wikidata_id: Optional[str] = None   # Q-item ID after entity linking, e.g. "Q42"
    confidence: float = 0.0


class CanonicalAnswer(BaseModel):
    """A single answer to a question."""
    answer_id: str
    body: str                           # cleaned plain text
    body_html: Optional[str] = None     # original HTML if available
    score: int = 0
    is_accepted: bool = False
    author_id: Optional[str] = None
    created_at: Optional[datetime] = None
    entity_mentions: list[EntityMention] = Field(default_factory=list)

    @field_validator("body")
    @classmethod
    def body_not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Answer body must not be empty")
        return v.strip()


class CanonicalQA(BaseModel):
    """
    Normalized QA record produced by every source mapper.

    Design decisions:
    - `id` is a UUID generated by the mapper; `source_id` is the original.
    - `content_hash` is SHA256 of (title + body + best answer body) for dedup.
    - `answers` are sorted by score descending; accepted answer first if available.
    - `entity_mentions` are populated by the enricher pipeline stage, not the mapper.
    - `duplicate_of` / `related_ids` reference other `id` values (canonical UUIDs),
      not source IDs — the deduplicator resolves source IDs to canonical IDs.
    """
    id: str                                         # UUID
    source: SourceName
    source_id: str                                  # original ID in source
    site: Optional[str] = None                      # SE site, e.g. "stackoverflow"

    title: str
    body: str                                       # cleaned plain text
    body_html: Optional[str] = None

    answers: list[CanonicalAnswer] = Field(default_factory=list)
    accepted_answer_id: Optional[str] = None        # references CanonicalAnswer.answer_id

    tags: list[str] = Field(default_factory=list)
    language: str = "en"
    score: int = 0
    view_count: Optional[int] = None
    answer_count: int = 0
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    # Graph linkage (populated during pipeline; uses canonical IDs)
    duplicate_of: Optional[str] = None
    related_ids: list[str] = Field(default_factory=list)
    entity_mentions: list[EntityMention] = Field(default_factory=list)

    # Provenance
    source_url: Optional[str] = None
    license: License = License.UNKNOWN
    content_hash: str = ""                          # set by compute_hash()

    # Arbitrary extra fields from the source (for lossless storage)
    extra: dict[str, Any] = Field(default_factory=dict)

    @field_validator("title")
    @classmethod
    def title_not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Title must not be empty")
        return v.strip()

    @model_validator(mode="after")
    def compute_hash(self) -> "CanonicalQA":
        """Compute content_hash if not already set."""
        if not self.content_hash:
            best_answer = self.best_answer
            key = json.dumps(
                {
                    "title": self.title,
                    "body": self.body,
                    "best_answer": best_answer.body if best_answer else "",
                },
                sort_keys=True,
                ensure_ascii=False,
            )
            self.content_hash = hashlib.sha256(key.encode()).hexdigest()
        return self

    @property
    def best_answer(self) -> Optional[CanonicalAnswer]:
        """Return accepted answer if present, else highest-scored answer."""
        if self.accepted_answer_id:
            for a in self.answers:
                if a.answer_id == self.accepted_answer_id:
                    return a
        return self.answers[0] if self.answers else None

    @property
    def sorted_answers(self) -> list[CanonicalAnswer]:
        """Answers sorted: accepted first, then by score descending."""
        accepted = [a for a in self.answers if a.is_accepted]
        rest = sorted(
            [a for a in self.answers if not a.is_accepted],
            key=lambda a: a.score,
            reverse=True,
        )
        return accepted + rest

    def attribution_str(self) -> str:
        """Return a short attribution string for CC BY-SA compliance."""
        parts = [f"Source: {self.source.value}"]
        if self.source_url:
            parts.append(f"URL: {self.source_url}")
        parts.append(f"License: {self.license.value}")
        return " | ".join(parts)
